@startuml
'https://plantuml.com/class-diagram

+class Configuracion_App{
    -String idioma
    -boolean notificaciones
    +Configuracion_App(String idioma, boolean notificaciones)
    +boolean validarIdioma()
    +boolean validarNotificaciones()
    +void mostrarConfiguracion()
}

@enduml